### ISSUE TITLE
Type 'Properties' does not satisfy the constraint 'CustomErrorProperties'.

### ISSUE THREAD

**Issue by MikeDabrowski** [adriengibrat/ts-custom-error#116]
We upgraded to Angular 15 and typescript 4.8.2 then this error started to appear. In our app this package is a subdependency of @zxing/library (checked their package.json and it seems to be there since 3yrs). 

```
Error: node_modules/ts-custom-error/dist/custom-error.d.ts:17:151 - error TS2344: Type 'Properties' does not satisfy the constraint 'CustomErrorProperties'.

17 export declare function customErrorFactory<Properties>(fn: CustomErrorFunction<Properties>,
 parent?: GenericErrorConstructor): CustomErrorConstructor<Properties>;   

  node_modules/ts-custom-error/dist/custom-error.d.ts:17:44
    17 export declare function customErrorFactory<Properties>(fn: CustomErrorFunction<Properties>, parent?: GenericErrorConstructor): CustomErrorConstructor<Properties>;
    This type parameter might need an `extends CustomErrorProperties` constraint.
```

I think this issue can be resolved by adding `extends` in the correct place, as the last line shows.

**Comment by adriengibrat** [comment]
Hello,

This issue is fixed since 3.2.1: see https://github.com/adriengibrat/ts-custom-error/commit/80f5eb08a1786ac397d6b7dd27e586e386dbe1ef
Maybe you could update @zxing/library to the latest version (the range in their master package.json accepts 3.2.1)
https://github.com/zxing-js/library/blob/master/package.json#L68
or you may try to add a overrides https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

Sorry for the inconvenience.

**Comment by MikeDabrowski** [comment]
Ah sorry then, I thought I checked the versions. I will make them a PR.
Thanks

**Comment by adriengibrat** [comment]
:+1: I'll close when you confirm it's fixed.

**Comment by MikeDabrowski** [comment]
Sorry it took me so long to respond. 

When I run npm ls it shows the latest version of ts-custom-error installed
```
`-- @zxing/library@0.19.2
  `-- ts-custom-error@3.3.1
```

I will try to use overrides and make that PR

**Comment by adriengibrat** [comment]
First try this:
> npm update ts-custom-error 

if it's not fixed use overrides

**Comment by adriengibrat** [comment]
First try this:
> npm update ts-custom-error 

if it's not fixed use overrides
