### ISSUE TITLE
WTFPL LIcense

### ISSUE THREAD

**Issue by ddramone** [adriengibrat/ts-custom-error#27]
"WTFPL" license is not acceptable for most of the companies because of legal and security risks associated with it.

I know it is a decision made by owner and you have 100% right to do so, but would you consider changing it to one of the OSI-approved licenses?

**Comment by adriengibrat** [comment]
I'm Ok to release under MIT licence.

The WTF licence was a way to clearly state that this is a pet project. I'm not actively using or maintaining this repository: 
it's, as stated on the README, a playground for automation release tools.

Even with proper licence, this project was not written with production use in mind 😅.

**Comment by ddramone** [comment]
That sounds great, i will wait for the release under `MIT`.

Thank you!
