### ISSUE TITLE
console.error(new CustomError) behaves unlike native Error

### ISSUE THREAD

**Issue by dilame** [adriengibrat/ts-custom-error#30]
```ts
import { CustomError } from 'ts-custom-error';
console.log(new Error('Hello'));
console.log(new CustomError('Hello'));
```

Result is

```
Error: Hello
    at /somewhere.ts:21:15

{ CustomError: Hello
    at /somewhere.ts:22:15
name: 'CustomError' }
```

The easy fix is to redefine `enumerable` descriptor for `name` property in `CustomError` constructor like 

```ts
Object.defineProperty(this, 'name', {
      value: new.target.name,
      enumerable: false,
    });
```

I think it should be done because user expect `CustomError` to behave like native `Error`, and it looks prettier and cleaner in console.

If you want, i can fix it and create PR.

**Comment by adriengibrat** [comment]
Thanks for this great feedback, it's fixed ;)

**Comment by dilame** [comment]
😄
