### ISSUE TITLE
NPM package contains 12.8MB `codeclimate-reporter` binary

### ISSUE THREAD

**Issue by ashleyw** [adriengibrat/ts-custom-error#32]
I assume this isn't meant to be in the final package tgz! :)

**Comment by adriengibrat** [comment]
Ouch!

I'm really sorry about that :scream: I'm releasing a patch immediatly.

**Comment by adriengibrat** [comment]
The issue exists since version 2.2.1 https://arve0.github.io/npm-download-size/#ts-custom-error@2.2.1

I'm deprecating old versions  (2.2.1 - 3.1.0) with a warning:

> npm package tarball contains useless codeclimate-reporter binary, please update to version 3.1.1. See https://github.com/adriengibrat/ts-custom-error/issues/32

Thanks a lot!
