### ISSUE TITLE
Extending CustomError should work like extending Error

### ISSUE THREAD

**Issue by CMCDragonkai** [adriengibrat/ts-custom-error#36]
```
import { CustomError } from 'ts-custom-error';

class ErrorSome extends CustomError { }

throw new ErrorSome('abc');
```

Should work given that the constructor can just be propagated. However typescript complains that it expects 0 arguments but got 1.

**Comment by CMCDragonkai** [comment]
It's annoying that I have to add a constructor just to do this:

```
import { CustomError } from 'ts-custom-error';

class ErrorSome extends CustomError {
  consructor (m) {
    super(m);
  }
}

throw new ErrorSome('abc');
```

**Comment by CMCDragonkai** [comment]
It seems like the reason this is happening is that the type of `CustomError` doesn't seem to be imported by typescript. Because I just tried this and it worked:

```
class CustomError extends Error {
  constructor(m) {
    super(m);
    this.name = new.target.name;
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

class ErrorImages extends CustomError {}

class ErrorImagesMissing extends ErrorImages {}
```

**Comment by adriengibrat** [comment]
How do you get this error?
-> from your IDE or from actual ts compilation?
Is there  tsconfig involved, I need to reproduce that  to try to fix it.

**Comment by CMCDragonkai** [comment]
It turns out that it's just a problem with my tsconfig. Closing.
