### ISSUE TITLE
BUG: Cannot assign to read only property 'name' of object 'ServerError

### ISSUE THREAD

**Issue by Val-istar-Guo** [adriengibrat/ts-custom-error#37]
typescript: 3.6.3
nodejs: 10.16.0

my code

```javascript

export class ServerError extends CustomError {
  expose: boolean

  status: number

  constructor(status: number, message: ErrorMessage = '') {
    super(message)
    this.status = status
    this.expose = true

    // Cannot assign to read only property 'name' of object 'ServerError'
    this.name = 'ServerError'
  }
}
```

**Comment by adriengibrat** [comment]
Hi, this is a really a bug: it's a nodejs feature ;)

 As the message states very clearly: 

*'name' is a read only property* 

of `Error`, extended by `CustomError` , extended by `ServerError`.

You can re-define name property by using 
```js
Object.defineProperty(this, 'name', {value: 'ServerError'});
```
instead of
```js
this.name = 'ServerError'
```

**Comment by Val-istar-Guo** [comment]
thanks

**Comment by adriengibrat** [comment]
yep, done https://github.com/adriengibrat/ts-custom-error/commit/f8ffe49fa0213fc5b29d7c261a4e2cae37ebc0fa

**Comment by JackCA** [comment]
I still get this in a browser environment

**Comment by adriengibrat** [comment]
Could you tell wich browser?

**Comment by JackCA** [comment]
I was getting:
```
Uncaught TypeError: Cannot redefine property: name
    at Object.defineProperty (<anonymous>)
    at defineProperty (define-property.js:4)
    at new FooError (errors.ts:21)
```

and after looking at what `defineProperty` was, I realize that this is passing through [core-js](https://github.com/zloirock/core-js) so it's not using the native definition.

It's possible that allowing redefinition is against the spec and this could break at any time?

**Comment by adriengibrat** [comment]
https://www.ecma-international.org/ecma-262/6.0/#sec-error.prototype.name
Not really explicit in the spec but Error.name is read-only in some old/strict implementations.

I try to know which ones, so the name and version of the browser would be a great start!

**Comment by JackCA** [comment]
Apologies, this was in Chrome 78.0.3904.108

**Comment by adriengibrat** [comment]
![image](https://user-images.githubusercontent.com/62407/69890343-6e988c00-12f5-11ea-887b-555af4275734.png)

https://codepen.io/adriengibrat/pen/yLyBVdO

with Chrome version 78.0.3904.108
