### ISSUE TITLE
Exception chaining/stack

### ISSUE THREAD

**Issue by CMCDragonkai** [adriengibrat/ts-custom-error#38]
I'm wondering if `ts-custom-error` can extend JS's native errors with the capability of doing exception stacking.

Basically similar to Python's `raise e from ...`. Where you can chain your exceptions.

This would be useful as often happens is that some exception comes from somewhere else, and you want to wrap that exception with your own exception but you still want to preserve the original exception.

**Comment by adriengibrat** [comment]
Have a look at https://github.com/mathew-kurian/TraceError.js

**Comment by adriengibrat** [comment]
Is anyone else interesting by this?

May be a good idea to add an example custom error that do exception stack... but not in the core source IMO.

**Comment by CMCDragonkai** [comment]
Actually v8 and TC39 standards now mean that JS has native cause chaining.
https://v8.dev/features/error-cause.ve

More info: https://stackoverflow.com/questions/22303633/set-error-cause-in-javascript-node-js Node.js (16.9+).

This means to support it, you just need to update your `CustomError` so that I can pass the `options` object in as well, and that will attach the cause object.

In order nodejs, the second parameter would just be ignored.

**Comment by adriengibrat** [comment]
Hello,

I did not saw your message, sorry...

this is awesome!
I'll have a look and i'm interested to add this feature. 
I need to figure out how to do it properly.

**Comment by adriengibrat** [comment]
@CMCDragonkai I introduced the support in https://github.com/adriengibrat/ts-custom-error/releases/tag/v3.3.0

Update of doc and improvements are still welcome ;)

**Comment by adriengibrat** [comment]
version 3.3.1 is compatible with Error option / cause & Exception chaining.
