### ISSUE TITLE
Example file need updates

### ISSUE THREAD

**Issue by TommySorensen** [adriengibrat/ts-custom-error#79]
Hi

It seems like the is a typescript error in the example file [here](https://github.com/adriengibrat/ts-custom-error/blob/main/src/example/http-error.ts)

The code `new HttpError(code, HttpError.messages[code]);` throws `Element implicitly has an 'any' type because expression of type 'number' can't be used to index type`

<img width="975" alt="image" src="https://user-images.githubusercontent.com/4134473/195042195-3f5981a1-34c1-48d4-b3eb-77b1acd74809.png">

```js
export class HttpError extends CustomError {
  protected static messages = {
    400: 'Bad Request',
  };

  public constructor(public code: number, message: string) {
    super(message);
  }

  public static fromCode(code: number) {
    return new HttpError(code, HttpError.messages[code]);
  }
}
```

**Comment by adriengibrat** [comment]
What about:

```ts
export class HttpError extends CustomError {
  protected static messages = {
    400: 'Bad Request',
    ...
  };

  public constructor(public code: number, message: string) {
    super(message);
  }

  public static fromCode(code: keyof typeof HttpError.messages) {
    return new HttpError(code, HttpError.messages[code]);
  }
}
```

**Comment by adriengibrat** [comment]
fixed with https://github.com/adriengibrat/ts-custom-error/commit/9e29873298e2c58dfdc24b262976ea9aa8138f90
